# Generated by Django 4.0.2 on 2022-03-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=8)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pedido', models.DateField()),
                ('cliente_nome', models.CharField(max_length=50)),
                ('cliente_endereco', models.CharField(max_length=50)),
                ('cliente_cep', models.CharField(max_length=10)),
            ],
        ),
    ]
