# Generated by Django 4.0.2 on 2022-03-08 18:26

from django.db import migrations, models
import django.db.models.deletion


def cria_cliente(apps, schema_editor):
    pedidos = apps.get_model("loja", "Pedido")
    clientes = apps.get_model("loja", "Cliente")
    for pedido in pedidos.objects.all():
        cliente, criado = clientes.objects.get_or_create(
            nome = pedido.cliente_nome,
            endereco = pedido.cliente_endereco,
            cep = pedido.cliente_cep,
        )
        pedido.cliente = cliente
        pedido.save()

def reverte_cria_cliente(apps, schema_editor):
    pedidos = apps.get_model("loja", "Pedido")
    for pedido in pedidos.objects.all():
        pedido.cliente_nome = pedido.cliente.nome
        pedido.cliente_endereco = pedido.cliente.endereco
        pedido.cliente_cep = pedido.cliente.cep
        pedido.save()


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [ #Criacao dos campos e flexibilizacao da estrutura
        migrations.CreateModel(
            name = "Cliente",
            fields = [
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name = 'pedido',
            name = 'cliente', 
            field = models.ForeignKey(
                null = True, #Importante pra poder criar a nova coluna na tabela e preencher futuramente
                on_delete = django.db.models.deletion.PROTECT,
                to = "loja.Cliente",
            )
        ),
        migrations.AlterField( # Liberando os campos para ficarem nulos
            model_name="pedido",
            name="cliente_endereco",
            field=models.CharField(null=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente_nome",
            field=models.CharField(null=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente_cep",
            field=models.CharField(null=True, max_length=10),
        ),

        migrations.RunPython(cria_cliente, reverse_code=reverte_cria_cliente),

        migrations.AlterField(
            model_name="Pedido",
            name="cliente",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="loja.Cliente",
            ),
        ),
        migrations.RemoveField(model_name="pedido", name="cliente_endereco",),
        migrations.RemoveField(model_name="pedido", name="cliente_nome",),
        migrations.RemoveField(model_name="pedido", name="cliente_cep",),
    ]


# https://blog.theodo.com/2020/05/django-migrations-without-losing-data/